# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64da74fa2dec1f304160ee42f723008e81ab8af6c5798ec6b3399c1833efa7eb3d2d8ca53645fa63c2d2970e4e5242abd24427ed3f7997be23718c4ba4a92c89

test:
  secret_key_base: 5228466446889552836ddbf61b4e8b0d15bb7a69a2813f9e73b3394eced7cc6b21cf4afad50639666982d655415a664d7063aef35433905083a6aad3d0e31fd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
